//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountManagement
    {
        public int Id_Account { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public int Id_Role { get; set; }
    }
}
