//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmAD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsmADEntities1 : DbContext
    {
        public AsmADEntities1()
            : base("name=AsmADEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountRole> AccountRoles { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseManagerment> CourseManagerments { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TraineeProfile> TraineeProfiles { get; set; }
        public virtual DbSet<TrainerProfile> TrainerProfiles { get; set; }
        public virtual DbSet<AccountManagement> AccountManagements { get; set; }
        public virtual DbSet<TopicVsTrainee> TopicVsTrainees { get; set; }
    }
}
