//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerProfile
    {
        public int Id_Trainer { get; set; }
        public string Name { get; set; }
        public bool ExOrInType { get; set; }
        public string Telephone { get; set; }
        public string EmailAddress { get; set; }
        public int Id_Topic { get; set; }
    }
}
